### ISSUE TITLE
small how-to mby?

### ISSUE THREAD

**Issue by llacqie** [kungfulon/fwgs-vgui2-support#1]
How  to compile all?

**Comment by wirke** [comment]
How to start cs interface?

**Comment by kungfulon** [comment]
Sorry for the late reply, but you can compile it using VS 2017. Just remember to clone submodules too. I don't remember how to install it since it was abandoned for a long time.

**Comment by ahmad12331233** [comment]
is it working????

**Comment by ahmad12331233** [comment]
i have vs 2019 can i build it or i need vs 2017 ???

**Comment by kungfulon** [comment]
https://github.com/kungfulon/xash3d-fwgs
